config/routes.rb
Ipdb::Application.routes.draw do
 
  resources :assets

  root :to => "home#index"

  devise_for :users

  resources :address_ranges
  resources :ips
  
  namespace :admin do
    resources :users do 
      get 'toggle_approval', :on => :member
      get 'toggle_admin', :on => :member  
    end
  end
end

app/models/address_range.rb
# == Schema Information
#
# Table name: address_ranges
#
#  id         :integer         not null, primary key
#  start_ip   :string(255)
#  end_ip     :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  ip_id      :integer
#

class AddressRange < ActiveRecord::Base
  has_many :ips, :foreign_key => :ip_id
  has_many :assets

  validates :start_ip, :end_ip,
      :presence => true, 
      :format => { :with => /\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/ }


  def full_name
    "#{start_ip} - #{end_ip}"
  end
end

app/controllers/address_ranges_controller.rb
class AddressRangesController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    @ranges = AddressRange.all
  end

  def show
    @range = AddressRange.find(params[:id])
  end

  def create
    @range = AddressRange.new(params[:address_range])

    respond_to do |format|
      if @range.save
        format.html { redirect_to @range, notice: 'IP Range was successfully created.' }
        format.json { render json: @range, status: :created, location: @range }
      else
        format.html { render action: "new" }
        format.json { render json: @range.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @range = AddressRange.new
  end

  def edit
    @range = AddressRange.find(params[:id])
  end

  def update
    @range = AddressRange.find(params[:id])

    respond_to do |format|
      if @range.update_attributes(params[:address_range])
        format.html { redirect_to address_ranges_path, notice: 'Range was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @range.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @range = AddressRange.find(params[:id])
    @range.destroy

    respond_to do |format|
      format.html { redirect_to address_ranges_url }
      format.json { head :no_content }
    end
  end
end

app/views/address_ranges/_form.html.erb
<%= form_for(@range) do |f| %>
  <% if @range.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@range.errors.count, "error") %> prohibited this range from being saved:</h2>

      <ul>
      <% @range.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_ip %><br />
    <%= f.text_field :start_ip %>
  </div>

  <div class="field">
    <%= f.label :end_ip %><br />
    <%= f.text_field :end_ip %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/address_ranges/edit.html.erb
<h1>Editing range</h1>

<%= render 'form' %>

<%= link_to 'Show', @range %> |
<%= link_to 'Back', address_ranges_path %>

app/views/address_ranges/index.html.erb
<h1>Listing IP Ranges</h1>

<table class="ranges-table">
  <tr>
    <th>Start</th>
    <th>End</th>
    <th></th>
    <th></th>
  </tr>

<% @ranges.each do |range| %>
  <tr>
    <td><%= range.start_ip %></td>
    <td><%= range.end_ip %></td>
    <td><%= link_to 'Edit', edit_address_range_path(range) %></td>
    <td><%= link_to 'Destroy', range, confirm: 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Range', new_address_range_path %>

app/views/address_ranges/new.html.erb
<h1>New range</h1>

<%= render 'form' %>

<%= link_to 'Back', address_ranges_path %>

app/views/address_ranges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Range:</b>
  <%= "#{@range.start_ip} + #{@range.end_ip}" %> 
</p>


<%= link_to 'Edit', edit_address_range_path(@range) %> |
<%= link_to 'Back', address_ranges_path %>