config/routes.rb
Ipdb::Application.routes.draw do
 
  resources :assets

  root :to => "home#index"

  devise_for :users

  resources :address_ranges
  resources :ips
  
  namespace :admin do
    resources :users do 
      get 'toggle_approval', :on => :member
      get 'toggle_admin', :on => :member  
    end
  end
end

app/models/asset.rb
# == Schema Information
#
# Table name: assets
#
#  id               :integer         not null, primary key
#  name             :string(255)
#  ip_id            :integer
#  address_range_id :integer
#  comments         :text
#  last_edit        :string(255)
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#

class Asset < ActiveRecord::Base
  belongs_to :ip

  validates :name, :last_edit, :presence => true

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assets }
    end
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
    @asset = Asset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.json
  def new
    @asset = Asset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(params[:asset])

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render json: @asset, status: :created, location: @asset }
      else
        format.html { render action: "new" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.json
  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to assets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for(@asset) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip_id %><br />
    <%= f.collection_select :ip_id, Ip.all, :id, :ip_name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <%= f.hidden_field :last_edit, :value => current_user.name %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<h1>Listing assets</h1>

<table class="assets-table">
  <tr>
    <th>Name</th>
    <th>Ip</th>
    <th>Address range</th>
    <th>Comments</th>
    <th>Last edited by</th>
    <th colspan="3">Actions</th>
  </tr>

<% @assets.each do |asset| %>
  <tr>
    <td><%= asset.name %></td>
    <% if asset.ip.nil? %>
    <td></td>
    <td></td>
    <% else %>
    <td><%= asset.ip.ip_name %></td>
    <td><%= asset.ip.address_range.full_name %></td>
    <% end %>
    <td><%= smart_truncate(asset.comments, :words => 5) %></td>
    <td><%= asset.last_edit %></td>
    <td><%= link_to 'Show', asset %></td>
    <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
    <td><%= link_to 'Destroy', asset, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @asset.name %>
</p>

<p>
  <b>Ip:</b>
  <%= @asset.ip_id %>
</p>

<p>
  <b>Address range:</b>
  <%= @asset.address_range_id %>
</p>

<p>
  <b>Comments:</b>
  <%= @asset.comments %>
</p>

<p>
  <b>Last edit:</b>
  <%= @asset.last_edit %>
</p>


<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>