config/routes.rb
Ipdb::Application.routes.draw do
 
  resources :assets

  root :to => "home#index"

  devise_for :users

  resources :address_ranges
  resources :ips
  
  namespace :admin do
    resources :users do 
      get 'toggle_approval', :on => :member
      get 'toggle_admin', :on => :member  
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  name                   :string(255)
#  admin                  :boolean         default(FALSE)
#  approved               :boolean         default(FALSE), not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :admin, :approved

  after_destroy :ensure_an_admin_remains
  
  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

private
  def ensure_an_admin_remains
    if User.where(:admin => true).count.zero?
      raise "Can't delete last admin"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!

  def new
    if !current_user.admin?
      redirect_to root_url, :alert => "Access Denied."
    else
      @user = User.new
    end
  end

  def index
    if !current_user.admin?
      redirect_to root_url, :alert => "Access Denied."
    else
    @users = User.all
    end
  end

  def edit
    if !current_user.admin?
      redirect_to root_url, :alert => "Access Denied."
    else
    @user = User.find(params[:id])
    end

    respond_to do |format|
      format.html
    end
  end

  def toggle_admin
    @user = User.find(params[:id])
    @user.toggle!(:admin)

    respond_to do |format|
      format.js
    end
  end

  def toggle_approval
    @user = User.find(params[:id])
    @user.toggle!(:approved)
  
    respond_to do |format|
      format.js
    end
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @User.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_url, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_admin_toggle.html.erb
<%= link_to "#{user.admin?}".capitalize!, toggle_admin_admin_user_path(user), :remote => true, :id => "admin_link_#{user.id}"%>

app/views/admin/users/_approval_toggle.html.erb
<%= link_to "#{user.approved? ? 'Disable': 'Approve'}", toggle_approval_admin_user_path(user), :remote => true, :id => "approval_link_#{user.id}"%>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p><%= f.label :name %><br />
<%= f.text_field :name %></p>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Users', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Registered Users</h1>
<p class ="users-blurb">Nb. You cannot demote or delete the currently logged in user.</p>
<table class="users-table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Admin?</th>
    <th colspan="2">Actions</th>
  </tr>
  <% @users.each do |a| %>
    <tr>
      <td><%= a.name %></td>
      <td><%= a.email %></td>
      <% if current_user.email == a.email %>
      <td><%= a.admin? ? 'True' : 'False' %></td>
      <td colspan="3"><%= link_to "Edit", edit_user_registration_path(a) %></td>
      <% else %>
      <td>
        <%= render :partial => 'admin/users/admin_toggle', :locals => { :user => a } %>
      </td>
      <td>
        <%= link_to "Edit", edit_admin_user_path(a) %>
      </td>
      <td class="approval-cell">
        <%= render :partial => 'admin/users/approval_toggle', :locals => { :user => a } %>
      </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/admin/users/toggle_admin.js.erb
$("#admin_link_<%= @user.id %>").html("<%=j @user.admin? ? 'True' : 'False' %>");

app/views/admin/users/toggle_approval.js.erb
$("#approval_link_<%= @user.id %>").html("<%=j @user.approved? ? 'Disable': 'Approve' %>");
window.stripeTable($('.users-table'));