config/routes.rb
Ipdb::Application.routes.draw do
 
  resources :assets

  root :to => "home#index"

  devise_for :users

  resources :address_ranges
  resources :ips
  
  namespace :admin do
    resources :users do 
      get 'toggle_approval', :on => :member
      get 'toggle_admin', :on => :member  
    end
  end
end

app/models/ip.rb
# == Schema Information
#
# Table name: ips
#
#  id               :integer         not null, primary key
#  ip_name          :string(255)
#  range_id         :integer
#  asset_id         :integer
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#  address_range_id :integer
#

class Ip < ActiveRecord::Base
  belongs_to :address_range, :foreign_key => :address_range_id
  has_one :asset

  validates :address_range, :ip_name, :presence => true
  validates :ip_name, :format => { :with => /\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/ }
end

app/controllers/ips_controller.rb
class IpsController < ApplicationController
  # GET /ips
  # GET /ips.json
  def index
    @ips = Ip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ips }
    end
  end

  # GET /ips/1
  # GET /ips/1.json
  def show
    @ip = Ip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ip }
    end
  end

  # GET /ips/new
  # GET /ips/new.json
  def new
    @ip = Ip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ip }
    end
  end

  # GET /ips/1/edit
  def edit
    @ip = Ip.find(params[:id])
  end

  # POST /ips
  # POST /ips.json
  def create
    @ip = Ip.new(params[:ip])

    respond_to do |format|
      if @ip.save
        format.html { redirect_to @ip, notice: 'Ip was successfully created.' }
        format.json { render json: @ip, status: :created, location: @ip }
      else
        format.html { render action: "new" }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ips/1
  # PUT /ips/1.json
  def update
    @ip = Ip.find(params[:id])

    respond_to do |format|
      if @ip.update_attributes(params[:ip])
        format.html { redirect_to @ip, notice: 'Ip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ips/1
  # DELETE /ips/1.json
  def destroy
    @ip = Ip.find(params[:id])
    @ip.destroy

    respond_to do |format|
      format.html { redirect_to ips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/i_ps_helper.rb
module IPsHelper
end

app/views/ips/_form.html.erb
<%= form_for(@ip) do |f| %>
  <% if @ip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ip.errors.count, "error") %> prohibited this ip from being saved:</h2>

      <ul>
      <% @ip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip_name %><br />
    <%= f.text_field :ip_name %>
  </div>
  <div class="field">
    <%= f.label :address_range_id %><br />
    <%= f.collection_select :address_range_id, AddressRange.all.collect, :id, :full_name, :prompt => "Please select IP", :blank => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ips/edit.html.erb
<h1>Editing ip</h1>

<%= render 'form' %>

<%= link_to 'Show', @ip %> |
<%= link_to 'Back', ips_path %>

app/views/ips/index.html.erb
<h1>Listing ips</h1>

<table class="ips-table">
  <tr>
    <th>IP</th>
    <th>Range</th>
    <th colspan="2">Actions</th>
  </tr>

<% @ips.each do |ip| %>
  <tr>
    <td><%= ip.ip_name %></td>
    <td><%= ip.address_range_id %></td>
    <td><%= link_to 'Edit', edit_ip_path(ip) %></td>
    <td><%= link_to 'Destroy', ip, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ip', new_ip_path %>

app/views/ips/new.html.erb
<h1>New ip</h1>

<%= render 'form' %>

<%= link_to 'Back', ips_path %>

app/views/ips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>IP:</b>
  <%= @ip.ip_name %>
</p>

<p>
  <b>Range:</b>
  <%= @ip.address_range.full_name %>
</p>

<%= link_to 'Edit', edit_ip_path(@ip) %> |
<%= link_to 'Back', ips_path %>